spring:
  datasource:
    url: jdbc:mysql://114.55.0.204:3306/compare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: compare
    password: compare
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081


alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000119649244
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpAX3ZCwK+ssBKNoV8MouKUuTfWt7B55oBUWUPfnb1nivQgA2ckSj/oCJ2sJxov00TJjTvRWseJGd9fNeMQjCakFvUtxGra8csJo58p7yxLP8sFwDdDfwdJlJ76k6rA650WlwNKVoGCh7mtiTMRATZjTrc7pKGkFzNX+sT+Fm1jzIhxItz75tFzDirFje9zV/bbIQSf+K8tGiVk/pjZMrrxDqQd/Kdxv8oS5SlI5F8STUZu91QsdDeA08gqKBORyfXbA14f0BTeTmGNH0FsWsve+CdR307Ziltzas0g+TMADLabPHFjWY3kG7FKrdL6R1RdXHu9rrvQIz0mZRi4wHRAgMBAAECggEACJ7x23NrVWzq0B5N2tL9OTYXRKlu+Xcl7PFI9WxfBxJla8JMb3McI0X43BMQN2uis9pcEuR4nVYADW+j0xzBO/EnLgeUmCjsRP1GgWdRAbyo24fk3GHNPXNp+7YtAx4x9O9zCJzWYb58awpZgC3sDWjd2s00njaY9UTySdd+Q/uPtNDC/BgnXe3oJ7R3wzZVQStDiUauHLoWtmY9KBw3SlOooJeYlY1KZrXtSlRHFsi8TZ0iK0YaYzKqdK8YLsdqFr39CdLFsxEIV9ClMdIrxpro1OTDWIyltByPhg4Zsn+f5BN4yc/VuHv9LObwkQn4oR7fRH+uajMVlR9ExzKAjQKBgQDarhPb2ywSGLh6AM6S/OFlAfN6+B6aR7zSw+7oBB3Y0jQqfI/Tp1zxdVDSWP+ye9XNpwZ5fAEpdbYW6Kw/n8+t892G6o7eAajE18L+PXEkg57v5MDAUIvAOqAu7bmOuZV/PmT6hUJlD9xkszm1xBY7Zo33nGJaUZ+aNChhfw6xEwKBgQDF2TJY/4VRujB0fanvDwYiP6olAzymKDh9WmqtQziYTxg4zEoM9JYDSNFA8AzKA8HQLg+xJLFyFg2IhauZIQ7hfKFN0xp2PgBJHsi3faLc25heoA1rkVWHY9xq2J+f7HxwFzebkM4kR6iUJf773YzDM+vQI1W+R5ftwiNnO8vCCwKBgCgPl+fBARPXn4QKPc3Dse71KouuhLyyw67A4jVy+5zK9W+LHjYiBO7fFQ1T7JPgB80C+jarNvNHczJDMbr+JeeyMzUSJ1YYa7iT5k75Jo8P5cAA4ibZGqD+nHW8ay/wY6jJ32ndm8oz26Y/ByV7ZK9BHGTuKz5skZaIU5V411ItAoGAc8PZxN+GV8LVFWRuKXYmBaYw3UVemG6SVy6vmr/pfp1RM/K9JYV7vWI/JnsPUKkQH8rD3cf1mCa1NnvYY1pHhcLR82KhaixvKFm94je+MvK+3idSku1QGU9iKpakGARc7412OS1qoSnYxw7QevkwowtfYMM8KYFksXbWFlKTr+8CgYEAxg0iTXqEgG98SboOJlQqQrpAsNXHxFbVtBDVjDtnPkTcLR9FXZdLXWn7Neg6gn9Fo/2+ohLhFfxpvrxBHUD8wnemX4STl1G+oTYjOkObnxMCLnarVy7FVOo/Fxu5kfguCqlQxWsUWmDL1wDtjHEvH0ImUJumRkUZnMYhZPIQYiA=
  publicKey:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo/L55yaCMq8ForNNg7P2LoSiTwoQF5+fr8oxK9yqfdldUsoOytOqcM5m2M02xaSfqOzH2IMVp3EAKV4tTfH9g1aa/YQvMafYnV1e2CxyGfjqmPwu3S86x/1Bl/hIq1fbPz9HpKRDU6Yrj2M4Bue53Iq6tiLZm6aXc63qbjwUgcWacEWZOOKFo4uGJDzDmteS8MC30SSViEBZj2OeqMROm8x+VaReaOY7hPfuG1dactISEUrKgICJukfKwYn5M/M3QD53qNevbJKos4wLgrdfnTnZYw7G0pd2pTwnQHfAKs9Qr9R8IrkC/LmYFd0XGJnNguVyHoNWIAoj8Ue3jsj/IQIDAQAB
  notifyUrl: http://508n4r4325.qicp.vip/notify
  returnUrl: http://localhost:8081/return
