spring:
  datasource:
    url: jdbc:mysql://114.55.0.204:3306/compare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: compare
    password: compare
  resources:
    static-locations: classpath:/static/
  redis:
    host: 114.55.0.204
    port: 6379
    password: nosugar
    lettuce:
      pool:
        max-active: 20



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080


alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000119649956
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCNnC90/oMUBbGNueE5vyd6KW8+8KrT62pIudcCjxoVRT9cW9Jc9uSwsMHGS7haRUQ7n0jOUeEj/Bm4fARS2q4ghpbGAq8WusobLGAXwFb4jfnn7g8tg/5BxR7C206/GeSsX87443tU8QcyR+YIRWC3nZMWP4SDs5+1NfOZRhm618SOvrA8G6cna7suLu9J5RXy8y5OyVNr/d0lqhvuwci2XK50Oegjdd+Jl9/DuulAIukWMjLRJgRt+NvfZFm/R/gDrxQo5EfjQRPFTAd6LGo2HKJCGM0r0brbZkhNPT2NrwKrWdQdUib7AGUqNkxQ6+xKDRr9nik9cuvaNa9yT0LbAgMBAAECggEAGRfM/QFAfuLHZKLEezQZLbd74/5HdwfnLH3p0KVE7PH5WUdYDmsdeQXJQHcYcr6Fab8+6nht2a+Jazxmk7v2UQMoYmwFVJTCzW/ekzbc8mxOFUAE5n7WJhdk7Qhpesl+0OClT0sYBqQzL0C4TUzl54N/ldiphaDlsvmdcdKPKqFeSoEnG5enfJn+sc073+v4LRfnDv4ApETyVWgc0A0RllTLveztZLnxb8EXr4VKUDtgHeI/SOkrKh912b0jMKarwkGsCDFaj+aw52S2C45mRsFmDMWCO1cb1U9HzYJD/TP5SSD+IGfIn24RqMB2bQqzek+q8nDcjzjCgxd6ZZ4JGQKBgQDrmBpn5b0owWIrULn2wFAlFDWSX6hPkDgAL2LC04Z4xg0hwAwTD8A9QCBdAdve25h6J4DfuMSsVAjBM+rHiAXnojCnGxrpS39f4AdWL576fcuZ/SR+lWYpTJOn9UnFZbcNku6tyGkowwQSWs+jZOwb+04qW61n6zmC+ZCIPEkVRQKBgQCZ4CWUqQSvBcgP28h7TPEEgpgK11Hfi6xSlRkHOvpgukWVgXDAbdz1EeGwMvV2mLRPSwzTnBtUdSSuKeB/VB3373MLd4ZACKlqC6JCwWIfhQExOU1513zCYHBqq6EqyuBhnfTga6lqsZxRmgd4BD7CumKAsH5vAY6pI8rLQycpnwKBgHLcpYMiLyc/oW0c3o2/FVP+ll/W42hnF+Z/M9do6ZbYeG6MA1cHxuIV8bFmxpvQ1HY57Esm+jxKfDo15bGCT96u5KmUPXqgpGlKAEm0zf2ydyGMmc5daIGaJCMvI9hpzuV/TX7MxvhonAOW4sT232aFD4b3S4Pu2wtQQXcqbTdBAoGABNbMt8Ec+ZgX84+43U/NIJQuzeB5nasZzzsLH3QWXaZd+9anQhXyZe6bB1yC5ajlurykeZ8mKODKN4PvoHF3w81O8+RdX3QmR8R35NuKB226XN7tddB2BvLbdi9RkTPyHH/ILKqWGFnfjZ1ncLnJc3xDDsL+JuWIo/8RKJVDDQcCgYBe3hLWhAbE0m+0hRRpb58e5Xvb1+mvJY9mIoDJ2lQGJG3HbS71c0rPnT2Fq+APoOfNSP/JVP3V4P4u717VWGq1B6akPge9DuWq6deaLtBYbCHtGqUMCXlshXkHrEfF06GlGICAUdhg/Mk/CVqMbfVfPbndzFrBSHMucOQJCtnn+g==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn31c2cJ0nuDEwQR/5kOsjq5bjgG2bRYG6URKVlQBISXFPvnGE6zV+QiTHChPAzxu/L8k3BpV1uWR1CwGY1MWQgsnTZomxPEuG/BHI6Cd/zuIw/uWvUTmnogfqgsBTzWuSjY0Vm3tQf+BMjrU+6dDFh/nz5nICoL8CMRblWGIgY9zRg1Wrm3fsK1nHTsRe4aces6xtbMlmYK5sqmUaHy84Gtgs0r2Sl4L6hsGF6amlWEMrdDGP5Qs07p0lRr2wlEib3b4P+72uoNepEY56DLnBuctTkfBbt83iEAhLtA6L1g/Fdm+j5MprL8rxtQQXjpXYAcM5kJ0ZPjOB9JH7t28zwIDAQAB
  notifyUrl: http://g5087572z8.zicp.vip/order-log/notify
  returnUrl: http://4wx878.natappfree.cc/succeed
